### ISSUE TITLE
about some Ops in pykan

### ISSUE THREAD

**Issue by JunL-Geek** [Jerry-Master/KAN-benchmarking#2]
Is the update_grid part of the official model implemented here?  And I think this is a very important part for the application of kan.

**Comment by Jerry-Master** [comment]
I just measure the execution time and memory of a two layer KAN of dimensions [input, hidden, 1] with a fixed grid size of 5. I don't think updating the grid is relevant here. Having a dynamic grid size means the number of parameters changes over time. In order to have a fair comparison we need to fix the number of parameters somehow. I agree that the other type of performance, the test loss, may be affected by that. But this repo is for efficiency measurement only.
