### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by Da1sypetals** [Jerry-Master/KAN-benchmarking#4]
I benchmarked my implementation of ChebyKAN written in CUDA.
The code runs slower than pure pytorch version and uses more VRAM, probably because the cuda code is not optimized.
- I added learnable parameter $k, b$ replacing $\tanh(x)$ with $\tanh(kx+b)$.

## Update: 
coalescing memory access (by altering dimension layout) made major improvements. In the table, df stands for degree-first, which has a similar meaning like batch-first.

---

Results:
```text

              |      forward  |     backward  |      forward  |     backward  |   num params  |  num trainable params
-----------------------------------------------------------------------------------------------------------------------
chebykan-gpu  |     53.51 ms  |     54.39 ms  |      1.94 GB  |      2.06 GB  |    167792640  |             167792640
cucheby-gpu   |     53.51 ms  |     51.20 ms  |      2.11 GB  |      2.24 GB  |    167792650  |             167792650
dfCu-gpu      |     20.72 ms  |     51.57 ms  |      1.38 GB  |      1.54 GB  |    167792650  |             167792650


```

The first row comes from the implementation [here](https://github.com/SynodicMonth/ChebyKAN/tree/7eb83592042e5d23c2aa338a0d3df9b54b5b6b19), while the last two are my implementations.

---

parameters are:
```text
batch size = 256
network: 5 layers, [2048, 2048, 2048, 2048, 2048, 1]
num repetitions = 100
```

My implementation: [cuChebyKAN](https://github.com/Da1sypetals/ChebyKan-cuda-op)
I am willing to learn any CUDA optimization tricks and happy to receive suggestions, and willing to receive optimization suggestions on my implementation 😄

**Comment by Jerry-Master** [comment]
Nice, but first, do you have a numerical check to be sure that the output of your layer is "exactly" the same as the original chebykan? In your code I did not see it. You can simply adapt mine from [here](https://github.com/Jerry-Master/KAN-benchmarking/blob/master/extra/check.py). 

Once you have that, the first suggestion that comes to my mind is the usage of shared memory. Your kernels are not using it. But, before doing more changes, you should also profile the kernel using nsight-compute to see where the bottlenecks are. There can be coalescing issues, or not enough occupancy, or the arithmetic intensity is low. And if you add shared memory you may encounter bank conflicts. You are blind unless you profile. In the [exercise 8 of cuda training series](https://github.com/olcf/cuda-training-series/tree/master/exercises/hw8) you have the metrics you need for optimizing memory bound applications.

As I said, the next big step is probably to use shared memory. But you can go further. If you feel like you want to go to the next level I recommend you have a look at [this blogpost](https://siboehm.com/articles/22/CUDA-MMM). There are also tricks not shown there, like warp shuffling. You can go as deep as you want.

When you check for the correctness of your approach, please try make a pull request in this repo so that I can add your implementation to it. I will be very thankful for the contribution.

**Comment by Da1sypetals** [comment]
Oops i did not notice the numerical check code! Thanks for mentioning that, and for the optimization suggestions, I will check them : )
